runtime: python311
entrypoint: gunicorn -b :$PORT osschain.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "osschain.settings"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: 300ms
  max_pending_latency: 400ms
