# Generated by Django 5.0.6 on 2024-10-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='destroy_accounts',
            new_name='DestroyAccounts',
        ),
    ]
