service: osschain-back-end
runtime: python311
entrypoint: gunicorn -b :$PORT Back.wsgi # Replace 'Back' with your Django project's name if different

env_variables:
  DJANGO_SETTINGS_MODULE: "Back.settings" # Confirm the correct Django settings module

handlers:
  - url: /static
    static_dir: static/ # Assumes 'python manage.py collectstatic' is used
  - url: /.*
    script: auto # Delegate requests to your application

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
