# Generated by Django 5.0.6 on 2024-07-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletListenerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100)),
                ('push_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PushNotifications',
        ),
    ]
